/*
  Copyright (c) 2010, Nicolas Garcia Belmonte
  All rights reserved

  > Redistribution and use in source and binary forms, with or without
  > modification, are permitted provided that the following conditions are met:
  >      * Redistributions of source code must retain the above copyright
  >        notice, this list of conditions and the following disclaimer.
  >      * Redistributions in binary form must reproduce the above copyright
  >        notice, this list of conditions and the following disclaimer in the
  >        documentation and/or other materials provided with the distribution.
  >      * Neither the name of the organization nor the
  >        names of its contributors may be used to endorse or promote products
  >        derived from this software without specific prior written permission.
  >
  >  THIS SOFTWARE IS PROVIDED BY NICOLAS GARCIA BELMONTE ``AS IS'' AND ANY
  >  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  >  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  >  DISCLAIMED. IN NO EVENT SHALL NICOLAS GARCIA BELMONTE BE LIABLE FOR ANY
  >  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
  >  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  >  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
  >  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  >  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  >  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
 
 (function(){window.$jit=function(a){a=a||window;for(var d in $jit)if($jit[d].$extend)a[d]=$jit[d]};$jit.version="2.0.0b";var h=function(a){return document.getElementById(a)};h.empty=function(){};h.extend=function(a,d){for(var c in d||{})a[c]=d[c];return a};h.lambda=function(a){return typeof a=="function"?a:function(){return a}};h.time=Date.now||function(){return+new Date};h.splat=function(a){var d=h.type(a);return d?d!="array"?[a]:a:[]};h.type=function(a){var d=h.type.s.call(a).match(/^\[object\s(.*)\]$/)[1].toLowerCase();
if(d!="object")return d;if(a&&a.$$family)return a.$$family;return a&&a.nodeName&&a.nodeType==1?"element":d};h.type.s=Object.prototype.toString;h.each=function(a,d){if(h.type(a)=="object")for(var c in a)d(a[c],c);else{c=0;for(var b=a.length;c<b;c++)d(a[c],c)}};h.indexOf=function(a,d){if(Array.indexOf)return a.indexOf(d);for(var c=0,b=a.length;c<b;c++)if(a[c]===d)return c;return-1};h.map=function(a,d){var c=[];h.each(a,function(b,e){c.push(d(b,e))});return c};h.reduce=function(a,d,c){var b=a.length;
if(b==0)return c;for(var e=arguments.length==3?c:a[--b];b--;)e=d(e,a[b]);return e};h.merge=function(){for(var a={},d=0,c=arguments.length;d<c;d++){var b=arguments[d];if(h.type(b)=="object")for(var e in b){var f=b[e],g=a[e];a[e]=g&&h.type(f)=="object"&&h.type(g)=="object"?h.merge(g,f):h.unlink(f)}}return a};h.unlink=function(a){var d;switch(h.type(a)){case "object":d={};for(var c in a)d[c]=h.unlink(a[c]);break;case "array":d=[];c=0;for(var b=a.length;c<b;c++)d[c]=h.unlink(a[c]);break;default:return a}return d};
h.zip=function(){if(arguments.length===0)return[];for(var a=0,d=[],c=arguments.length,b=arguments[0].length;a<b;a++){for(var e=0,f=[];e<c;e++)f.push(arguments[e][a]);d.push(f)}return d};h.rgbToHex=function(a,d){if(a.length<3)return null;if(a.length==4&&a[3]==0&&!d)return"transparent";for(var c=[],b=0;b<3;b++){var e=(a[b]-0).toString(16);c.push(e.length==1?"0"+e:e)}return d?c:"#"+c.join("")};h.hexToRgb=function(a){if(a.length!=7){a=a.match(/^#?(\w{1,2})(\w{1,2})(\w{1,2})$/);a.shift();if(a.length!=
3)return null;for(var d=[],c=0;c<3;c++){var b=a[c];if(b.length==1)b+=b;d.push(parseInt(b,16))}return d}else{a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]}};h.destroy=function(a){h.clean(a);a.parentNode&&a.parentNode.removeChild(a);a.clearAttributes&&a.clearAttributes()};h.clean=function(a){a=a.childNodes;for(var d=0,c=a.length;d<c;d++)h.destroy(a[d])};h.addEvent=function(a,d,c){a.addEventListener?a.addEventListener(d,c,false):a.attachEvent("on"+d,c)};h.addEvents=function(a,d){for(var c in d)h.addEvent(a,
c,d[c])};h.hasClass=function(a,d){return(" "+a.className+" ").indexOf(" "+d+" ")>-1};h.addClass=function(a,d){if(!h.hasClass(a,d))a.className=a.className+" "+d};h.removeClass=function(a,d){a.className=a.className.replace(RegExp("(^|\\s)"+d+"(?:\\s|$)"),"$1")};h.getPos=function(a){var d=function(c){for(var b={x:0,y:0};c&&!/^(?:body|html)$/i.test(c.tagName);){b.x+=c.offsetLeft;b.y+=c.offsetTop;c=c.offsetParent}return b}(a);a=function(c){for(var b={x:0,y:0};c&&!/^(?:body|html)$/i.test(c.tagName);){b.x+=
c.scrollLeft;b.y+=c.scrollTop;c=c.parentNode}return b}(a);return{x:d.x-a.x,y:d.y-a.y}};h.event={get:function(a,d){d=d||window;return a||d.event},getWheel:function(a){return a.wheelDelta?a.wheelDelta/120:-(a.detail||0)/3},isRightClick:function(a){return a.which==3||a.button==2},getPos:function(a,d){d=d||window;a=a||d.event;var c=d.document;c=c.documentElement||c.body;if(a.touches&&a.touches.length)a=a.touches[0];return{x:a.pageX||a.clientX+c.scrollLeft,y:a.pageY||a.clientY+c.scrollTop}},stop:function(a){a.stopPropagation&&
a.stopPropagation();a.cancelBubble=true;if(a.preventDefault)a.preventDefault();else a.returnValue=false}};$jit.util=$jit.id=h;var q=function(a){a=a||{};var d=function(){for(var b in this)if(typeof this[b]!="function")this[b]=h.unlink(this[b]);this.constructor=d;if(q.prototyping)return this;b=this.initialize?this.initialize.apply(this,arguments):this;this.$$family="class";return b};for(var c in q.Mutators)if(a[c]){a=q.Mutators[c](a,a[c]);delete a[c]}h.extend(d,this);d.constructor=q;d.prototype=a;return d};
q.Mutators={Implements:function(a,d){h.each(h.splat(d),function(c){q.prototyping=c;c=typeof c=="function"?new c:c;for(var b in c)b in a||(a[b]=c[b]);delete q.prototyping});return a}};h.extend(q,{inherit:function(a,d){for(var c in d){var b=d[c],e=a[c],f=h.type(b);if(e&&f=="function")b!=e&&q.override(a,c,b);else a[c]=f=="object"?h.merge(e,b):b}return a},override:function(a,d,c){var b=q.prototyping;if(b&&a[d]!=b[d])b=null;a[d]=function(){var e=this.parent;this.parent=b?b[d]:a[d];var f=c.apply(this,arguments);
this.parent=e;return f}}});q.prototype.implement=function(){var a=this.prototype;h.each(Array.prototype.slice.call(arguments||[]),function(d){q.inherit(a,d)});return this};$jit.Class=q;$jit.json={prune:function(a,d){this.each(a,function(c,b){if(b==d&&c.children){delete c.children;c.children=[]}})},getParent:function(a,d){if(a.id==d)return false;var c=a.children;if(c&&c.length>0)for(var b=0;b<c.length;b++)if(c[b].id==d)return a;else{var e=this.getParent(c[b],d);if(e)return e}return false},getSubtree:function(a,
d){if(a.id==d)return a;for(var c=0,b=a.children;c<b.length;c++){var e=this.getSubtree(b[c],d);if(e!=null)return e}return null},eachLevel:function(a,d,c,b){if(d<=c){b(a,d);if(a.children){var e=0;for(a=a.children;e<a.length;e++)this.eachLevel(a[e],d+1,c,b)}}},each:function(a,d){this.eachLevel(a,0,Number.MAX_VALUE,d)}};$jit.Trans={$extend:true,linear:function(a){return a}};var I=$jit.Trans;(function(){var a=function(d,c){c=h.splat(c);return h.extend(d,{easeIn:function(b){return d(b,c)},easeOut:function(b){return 1-
d(1-b,c)},easeInOut:function(b){return b<=0.5?d(2*b,c)/2:(2-d(2*(1-b),c))/2}})};h.each({Pow:function(d,c){return Math.pow(d,c[0]||6)},Expo:function(d){return Math.pow(2,8*(d-1))},Circ:function(d){return 1-Math.sin(Math.acos(d))},Sine:function(d){return 1-Math.sin((1-d)*Math.PI/2)},Back:function(d,c){c=c[0]||1.618;return Math.pow(d,2)*((c+1)*d-c)},Bounce:function(d){for(var c,b=0,e=1;;b+=e,e/=2)if(d>=(7-4*b)/11){c=e*e-Math.pow((11-6*b-11*d)/4,2);break}return c},Elastic:function(d,c){return Math.pow(2,
10*--d)*Math.cos(20*d*Math.PI*(c[0]||1)/3)}},function(d,c){I[c]=a(d)});h.each(["Quad","Cubic","Quart","Quint"],function(d,c){I[d]=a(function(b){return Math.pow(b,[c+2])})})})();var O=new q({initialize:function(a){this.setOptions(a)},setOptions:function(a){this.opt=h.merge({duration:2500,fps:40,transition:I.Quart.easeInOut,compute:h.empty,complete:h.empty,link:"ignore"},a||{});return this},step:function(){var a=h.time(),d=this.opt;if(a<this.time+d.duration){a=d.transition((a-this.time)/d.duration);
d.compute(a)}else{this.timer=clearInterval(this.timer);d.compute(1);d.complete()}},start:function(){if(!this.check())return this;this.time=0;this.startTimer();return this},startTimer:function(){var a=this,d=this.opt.fps;if(this.timer)return false;this.time=h.time()-this.time;this.timer=setInterval(function(){a.step()},Math.round(1E3/d));return true},pause:function(){this.stopTimer();return this},resume:function(){this.startTimer();return this},stopTimer:function(){if(!this.timer)return false;this.time=
h.time()-this.time;this.timer=clearInterval(this.timer);return true},check:function(){if(!this.timer)return true;if(this.opt.link=="cancel"){this.stopTimer();return true}return false}}),A=function(){for(var a=arguments,d=0,c=a.length,b={};d<c;d++){var e=A[a[d]];if(e.$extend)h.extend(b,e);else b[a[d]]=e}return b};A.Canvas={$extend:true,injectInto:"id",width:false,height:false,useCanvas:false,withLabels:true,background:false};A.Tree={$extend:true,orientation:"left",subtreeOffset:8,siblingOffset:5,indent:10,
multitree:false,align:"center"};A.Node={$extend:false,overridable:false,type:"circle",color:"#ccb",alpha:1,dim:3,height:20,width:90,autoHeight:false,autoWidth:false,lineWidth:1,transform:true,align:"center",angularWidth:1,span:1,CanvasStyles:{}};A.Edge={$extend:false,overridable:false,type:"line",color:"#ccb",lineWidth:1,dim:15,alpha:1,epsilon:7,CanvasStyles:{}};A.Fx={$extend:true,fps:40,duration:2500,transition:$jit.Trans.Quart.easeInOut,clearCanvas:true};A.Label={$extend:false,overridable:false,
type:"HTML",style:" ",size:10,family:"sans-serif",textAlign:"center",textBaseline:"alphabetic",color:"#fff"};A.Tips={$extend:false,enable:false,type:"auto",offsetX:20,offsetY:20,force:false,onShow:h.empty,onHide:h.empty};A.NodeStyles={$extend:false,enable:false,type:"auto",stylesHover:false,stylesClick:false};A.Events={$extend:false,enable:false,enableForEdges:false,type:"auto",onClick:h.empty,onRightClick:h.empty,onMouseMove:h.empty,onMouseEnter:h.empty,onMouseLeave:h.empty,onDragStart:h.empty,onDragMove:h.empty,
onDragCancel:h.empty,onDragEnd:h.empty,onTouchStart:h.empty,onTouchMove:h.empty,onTouchEnd:h.empty,onMouseWheel:h.empty};A.Navigation={$extend:false,enable:false,type:"auto",panning:false,zooming:false};A.Controller={$extend:true,onBeforeCompute:h.empty,onAfterCompute:h.empty,onCreateLabel:h.empty,onPlaceLabel:h.empty,onComplete:h.empty,onBeforePlotLine:h.empty,onAfterPlotLine:h.empty,onBeforePlotNode:h.empty,onAfterPlotNode:h.empty,request:false};var J={initialize:function(a,d){this.viz=d;this.canvas=
d.canvas;this.config=d.config[a];this.nodeTypes=d.fx.nodeTypes;var c=this.config.type;this.labelContainer=(this.dom=c=="auto"?d.config.Label.type!="Native":c!="Native")&&d.labels.getLabelContainer();this.isEnabled()&&this.initializePost()},initializePost:h.empty,setAsProperty:h.lambda(false),isEnabled:function(){return this.config.enable},isLabel:function(a,d){a=h.event.get(a,d);var c=this.labelContainer,b=a.target||a.srcElement;if(b&&b.parentNode==c)return b;return false}},K={onMouseUp:h.empty,onMouseDown:h.empty,
onMouseMove:h.empty,onMouseOver:h.empty,onMouseOut:h.empty,onMouseWheel:h.empty,onTouchStart:h.empty,onTouchMove:h.empty,onTouchEnd:h.empty,onTouchCancel:h.empty},Y=new q({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.edge=this.node=false;this.registeredObjects=[];this.attachEvents()},attachEvents:function(){var a=this.canvas.getElement(),d=this;a.oncontextmenu=h.lambda(false);h.addEvents(a,{mouseup:function(b,e){var f=h.event.get(b,e);d.handleEvent("MouseUp",b,e,d.makeEventObject(b,
e),h.event.isRightClick(f))},mousedown:function(b,e){var f=h.event.get(b,e);d.handleEvent("MouseDown",b,e,d.makeEventObject(b,e),h.event.isRightClick(f))},mousemove:function(b,e){d.handleEvent("MouseMove",b,e,d.makeEventObject(b,e))},mouseover:function(b,e){d.handleEvent("MouseOver",b,e,d.makeEventObject(b,e))},mouseout:function(b,e){d.handleEvent("MouseOut",b,e,d.makeEventObject(b,e))},touchstart:function(b,e){d.handleEvent("TouchStart",b,e,d.makeEventObject(b,e))},touchmove:function(b,e){d.handleEvent("TouchMove",
b,e,d.makeEventObject(b,e))},touchend:function(b,e){d.handleEvent("TouchEnd",b,e,d.makeEventObject(b,e))}});var c=function(b,e){var f=h.event.get(b,e);f=h.event.getWheel(f);d.handleEvent("MouseWheel",b,e,f)};!document.getBoxObjectFor&&window.mozInnerScreenX==null?h.addEvent(a,"mousewheel",c):a.addEventListener("DOMMouseScroll",c,false)},register:function(a){this.registeredObjects.push(a)},handleEvent:function(){for(var a=Array.prototype.slice.call(arguments),d=a.shift(),c=0,b=this.registeredObjects,
e=b.length;c<e;c++)b[c]["on"+d].apply(b[c],a)},makeEventObject:function(a,d){var c=this,b=this.viz.graph,e=this.viz.fx,f=e.nodeTypes,g=e.edgeTypes;return{pos:false,node:false,edge:false,contains:false,getNodeCalled:false,getEdgeCalled:false,getPos:function(){var i=c.viz.canvas,j=i.getSize(),k=i.getPos(),l=i.translateOffsetX,n=i.translateOffsetY,m=i.scaleOffsetX;i=i.scaleOffsetY;var o=h.event.getPos(a,d);return this.pos={x:(o.x-k.x-j.width/2-l)*1/m,y:(o.y-k.y-j.height/2-n)*1/i}},getNode:function(){if(this.getNodeCalled)return this.node;
this.getNodeCalled=true;for(var i in b.nodes){var j=b.nodes[i],k=j&&f[j.getData("type")];if(k=k&&k.contains&&k.contains.call(e,j,this.getPos())){this.contains=k;return c.node=this.node=j}}return c.node=this.node=false},getEdge:function(){if(this.getEdgeCalled)return this.edge;this.getEdgeCalled=true;var i={};for(var j in b.edges){var k=b.edges[j];i[j]=true;for(var l in k)if(!(l in i)){var n=k[l],m=n&&g[n.getData("type")];if(m=m&&m.contains&&m.contains.call(e,n,this.getPos())){this.contains=m;return c.edge=
this.edge=n}}}return c.edge=this.edge=false},getContains:function(){if(this.getNodeCalled)return this.contains;this.getNode();return this.contains}}}}),E={initializeExtras:function(){var a=new Y(this),d=this;h.each(["NodeStyles","Tips","Navigation","Events"],function(c){var b=new E.Classes[c](c,d);b.isEnabled()&&a.register(b);if(b.setAsProperty())d[c.toLowerCase()]=b})}};E.Classes={};E.Classes.Events=new q({Implements:[J,K],initializePost:function(){this.fx=this.viz.fx;this.ntypes=this.viz.fx.nodeTypes;
this.etypes=this.viz.fx.edgeTypes;this.moved=this.touchMoved=this.touched=this.pressed=this.hovered=false},setAsProperty:h.lambda(true),onMouseUp:function(a,d,c,b){a=h.event.get(a,d);this.moved||(b?this.config.onRightClick(this.hovered,c,a):this.config.onClick(this.pressed,c,a));if(this.pressed){this.moved?this.config.onDragEnd(this.pressed,c,a):this.config.onDragCancel(this.pressed,c,a);this.pressed=this.moved=false}},onMouseOut:function(a,d,c){var b=h.event.get(a,d),e;if(this.dom&&(e=this.isLabel(a,
d))){this.config.onMouseLeave(this.viz.graph.getNode(e.id),c,b);this.hovered=false}else{a=b.relatedTarget;for(d=this.canvas.getElement();a&&a.parentNode;){if(d==a.parentNode)return;a=a.parentNode}if(this.hovered){this.config.onMouseLeave(this.hovered,c,b);this.hovered=false}}},onMouseOver:function(a,d,c){var b=h.event.get(a,d),e;if(this.dom&&(e=this.isLabel(a,d))){this.hovered=this.viz.graph.getNode(e.id);this.config.onMouseEnter(this.hovered,c,b)}},onMouseMove:function(a,d,c){a=h.event.get(a,d);
if(this.pressed){this.moved=true;this.config.onDragMove(this.pressed,c,a)}else if(this.dom)this.config.onMouseMove(this.hovered,c,a);else{if(this.hovered){d=this.hovered;var b=d.nodeFrom?this.etypes[d.getData("type")]:this.ntypes[d.getData("type")];if(b&&b.contains&&b.contains.call(this.fx,d,c.getPos())){this.config.onMouseMove(d,c,a);return}else{this.config.onMouseLeave(d,c,a);this.hovered=false}}(this.hovered=c.getNode()||this.config.enableForEdges&&c.getEdge())?this.config.onMouseEnter(this.hovered,
c,a):this.config.onMouseMove(false,c,a)}},onMouseWheel:function(a,d,c){this.config.onMouseWheel(c,h.event.get(a,d))},onMouseDown:function(a,d,c){a=h.event.get(a,d);this.pressed=c.getNode()||this.config.enableForEdges&&c.getEdge();this.config.onDragStart(this.pressed,c,a)},onTouchStart:function(a,d,c){a=h.event.get(a,d);this.touched=c.getNode()||this.config.enableForEdges&&c.getEdge();this.config.onTouchStart(this.touched,c,a)},onTouchMove:function(a,d,c){a=h.event.get(a,d);if(this.touched){this.touchMoved=
true;this.config.onTouchMove(this.touched,c,a)}},onTouchEnd:function(a,d,c){a=h.event.get(a,d);if(this.touched){this.touchMoved?this.config.onTouchEnd(this.touched,c,a):this.config.onTouchCancel(this.touched,c,a);this.touched=this.touchMoved=false}}});E.Classes.Tips=new q({Implements:[J,K],initializePost:function(){if(document.body){var a=h("_tooltip")||document.createElement("div");a.id="_tooltip";a.className="tip";h.extend(a.style,{position:"absolute",display:"none",zIndex:13E3});document.body.appendChild(a);
this.tip=a;this.node=false}},setAsProperty:h.lambda(true),onMouseOut:function(a,d){if(this.dom&&this.isLabel(a,d))this.hide(true);else{for(var c=a.relatedTarget,b=this.canvas.getElement();c&&c.parentNode;){if(b==c.parentNode)return;c=c.parentNode}this.hide(false)}},onMouseOver:function(a,d){var c;if(this.dom&&(c=this.isLabel(a,d))){this.node=this.viz.graph.getNode(c.id);this.config.onShow(this.tip,this.node,c)}},onMouseMove:function(a,d,c){this.dom&&this.isLabel(a,d)&&this.setTooltipPosition(h.event.getPos(a,
d));if(!this.dom){var b=c.getNode();if(b){if(this.config.force||!this.node||this.node.id!=b.id){this.node=b;this.config.onShow(this.tip,b,c.getContains())}this.setTooltipPosition(h.event.getPos(a,d))}else this.hide(true)}},setTooltipPosition:function(a){var d=this.tip,c=d.style,b=this.config;c.display="";var e={height:document.body.clientHeight,width:document.body.clientWidth};d={width:d.offsetWidth,height:d.offsetHeight};var f=b.offsetX;b=b.offsetY;c.top=(a.y+b+d.height>e.height?a.y-d.height-b:a.y+
b)+"px";c.left=(a.x+d.width+f>e.width?a.x-d.width-f:a.x+f)+"px"},hide:function(a){this.tip.style.display="none";a&&this.config.onHide()}});E.Classes.NodeStyles=new q({Implements:[J,K],initializePost:function(){this.fx=this.viz.fx;this.types=this.viz.fx.nodeTypes;this.nStyles=this.config;this.nodeStylesOnHover=this.nStyles.stylesHover;this.nodeStylesOnClick=this.nStyles.stylesClick;this.hoveredNode=false;this.fx.nodeFxAnimation=new O;this.move=this.down=false},onMouseOut:function(a,d){this.down=this.move=
false;if(this.hoveredNode){this.dom&&this.isLabel(a,d)&&this.toggleStylesOnHover(this.hoveredNode,false);for(var c=a.relatedTarget,b=this.canvas.getElement();c&&c.parentNode;){if(b==c.parentNode)return;c=c.parentNode}this.toggleStylesOnHover(this.hoveredNode,false);this.hoveredNode=false}},onMouseOver:function(a,d){var c;if(this.dom&&(c=this.isLabel(a,d))){c=this.viz.graph.getNode(c.id);if(!c.selected){this.hoveredNode=c;this.toggleStylesOnHover(this.hoveredNode,true)}}},onMouseDown:function(a,d,
c,b){if(!b){var e;if(this.dom&&(e=this.isLabel(a,d)))this.down=this.viz.graph.getNode(e.id);else if(!this.dom)this.down=c.getNode();this.move=false}},onMouseUp:function(a,d,c,b){if(!b){this.move||this.onClick(c.getNode());this.down=this.move=false}},getRestoredStyles:function(a,d){var c={},b=this["nodeStylesOn"+d];for(var e in b)c[e]=a.styles["$"+e];return c},toggleStylesOnHover:function(a,d){this.nodeStylesOnHover&&this.toggleStylesOn("Hover",a,d)},toggleStylesOnClick:function(a,d){this.nodeStylesOnClick&&
this.toggleStylesOn("Click",a,d)},toggleStylesOn:function(a,d,c){var b=this.viz;if(c){if(!d.styles)d.styles=h.merge(d.data,{});for(var e in this["nodeStylesOn"+a]){c="$"+e;c in d.styles||(d.styles[c]=d.getData(e))}b.fx.nodeFx(h.extend({elements:{id:d.id,properties:this["nodeStylesOn"+a]},transition:I.Quart.easeOut,duration:300,fps:40},this.config))}else{a=this.getRestoredStyles(d,a);b.fx.nodeFx(h.extend({elements:{id:d.id,properties:a},transition:I.Quart.easeOut,duration:300,fps:40},this.config))}},
onClick:function(a){if(a){var d=this.nodeStylesOnClick;if(d)if(a.selected){this.toggleStylesOnClick(a,false);delete a.selected}else{this.viz.graph.eachNode(function(c){if(c.selected){for(var b in d)c.setData(b,c.styles["$"+b],"end");delete c.selected}});this.toggleStylesOnClick(a,true);a.selected=true;delete a.hovered;this.hoveredNode=false}}},onMouseMove:function(a,d,c){if(this.down)this.move=true;if(!(this.dom&&this.isLabel(a,d))){var b=this.nodeStylesOnHover;if(b)if(!this.dom){if(this.hoveredNode)if((a=
this.types[this.hoveredNode.getData("type")])&&a.contains&&a.contains.call(this.fx,this.hoveredNode,c.getPos()))return;c=c.getNode();if(this.hoveredNode||c)if(!c.hovered)if(c&&!c.selected){this.fx.nodeFxAnimation.stopTimer();this.viz.graph.eachNode(function(e){if(e.hovered&&!e.selected){for(var f in b)e.setData(f,e.styles["$"+f],"end");delete e.hovered}});c.hovered=true;this.hoveredNode=c;this.toggleStylesOnHover(c,true)}else if(this.hoveredNode&&!this.hoveredNode.selected){this.fx.nodeFxAnimation.stopTimer();
this.toggleStylesOnHover(this.hoveredNode,false);delete this.hoveredNode.hovered;this.hoveredNode=false}}}}});E.Classes.Navigation=new q({Implements:[J,K],initializePost:function(){this.pressed=this.pos=false},onMouseWheel:function(a,d,c){if(this.config.zooming){h.event.stop(h.event.get(a,d));a=1+c*(this.config.zooming/1E3);this.canvas.scale(a,a)}},onMouseDown:function(a,d,c){if(this.config.panning)if(!(this.config.panning=="avoid nodes"&&c.getNode())){this.pressed=true;this.pos=c.getPos();a=this.canvas;
d=a.translateOffsetX;c=a.translateOffsetY;var b=a.scaleOffsetY;this.pos.x*=a.scaleOffsetX;this.pos.x+=d;this.pos.y*=b;this.pos.y+=c}},onMouseMove:function(a,d,c){if(this.config.panning)if(this.pressed)if(!(this.config.panning=="avoid nodes"&&c.getNode())){a=this.pos;c=c.getPos();var b=this.canvas,e=b.translateOffsetX,f=b.translateOffsetY;d=b.scaleOffsetX;b=b.scaleOffsetY;c.x*=d;c.y*=b;c.x+=e;c.y+=f;e=c.x-a.x;a=c.y-a.y;this.pos=c;this.canvas.translate(e*1/d,a*1/b)}},onMouseUp:function(){if(this.config.panning)this.pressed=
false}});var C;(function(){function a(b,e){var f=document.createElement(b);for(var g in e)if(typeof e[g]=="object")h.extend(f[g],e[g]);else f[g]=e[g];if(b=="canvas"&&!c&&G_vmlCanvasManager)f=G_vmlCanvasManager.initElement(document.body.appendChild(f));return f}var d=typeof HTMLCanvasElement,c=d=="object"||d=="function";$jit.Canvas=C=new q({canvases:[],pos:false,element:false,labelContainer:false,translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(b,e){this.viz=
b;this.opt=e;var f=h.type(e.injectInto)=="string"?e.injectInto:e.injectInto.id,g=f+"-label",i=h(f),j=e.width||i.offsetWidth,k=e.height||i.offsetHeight;this.id=f;var l={injectInto:f,width:j,height:k};this.element=a("div",{id:f+"-canvaswidget",style:{position:"relative",width:j+"px",height:k+"px"}});this.labelContainer=this.createLabelContainer(e.Label.type,g,l);this.canvases.push(new C.Base({config:h.extend({idSuffix:"-canvas"},l),plot:function(){b.fx.plot()},resize:function(){b.refresh()}}));if(f=
e.background){l=new C.Background[f.type](b,h.extend(f,l));this.canvases.push(new C.Base(l))}for(l=this.canvases.length;l--;){this.element.appendChild(this.canvases[l].canvas);l>0&&this.canvases[l].plot()}this.element.appendChild(this.labelContainer);i.appendChild(this.element);var n=null,m=this;h.addEvent(window,"scroll",function(){clearTimeout(n);n=setTimeout(function(){m.getPos(true)},500)})},getCtx:function(b){return this.canvases[b||0].getCtx()},getConfig:function(){return this.opt},getElement:function(){return this.element},
getSize:function(b){return this.canvases[b||0].getSize()},resize:function(b,e){this.getPos(true);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;for(var f=0,g=this.canvases.length;f<g;f++)this.canvases[f].resize(b,e);f=this.element.style;f.width=b+"px";f.height=e+"px";if(this.labelContainer)this.labelContainer.style.width=b+"px"},translate:function(b,e,f){this.translateOffsetX+=b*this.scaleOffsetX;this.translateOffsetY+=e*this.scaleOffsetY;for(var g=0,i=this.canvases.length;g<
i;g++)this.canvases[g].translate(b,e,f)},scale:function(b,e){var f=this.scaleOffsetX*b,g=this.scaleOffsetY*e,i=this.translateOffsetX*(b-1)/f,j=this.translateOffsetY*(e-1)/g;this.scaleOffsetX=f;this.scaleOffsetY=g;f=0;for(g=this.canvases.length;f<g;f++)this.canvases[f].scale(b,e,true);this.translate(i,j,false)},getPos:function(b){if(b||!this.pos)return this.pos=h.getPos(this.getElement());return this.pos},clear:function(b){this.canvases[b||0].clear()},path:function(b,e){var f=this.canvases[0].getCtx();
f.beginPath();e(f);f[b]();f.closePath()},createLabelContainer:function(b,e,f){if(b=="HTML"||b=="Native")return a("div",{id:e,style:{overflow:"visible",position:"absolute",top:0,left:0,width:f.width+"px",height:0}});else if(b=="SVG"){b=document.createElementNS("http://www.w3.org/2000/svg","svg:svg");b.setAttribute("width",f.width);b.setAttribute("height",f.height);var g=b.style;g.position="absolute";g.left=g.top="0px";g=document.createElementNS("http://www.w3.org/2000/svg","svg:g");g.setAttribute("width",
f.width);g.setAttribute("height",f.height);g.setAttribute("x",0);g.setAttribute("y",0);g.setAttribute("id",e);b.appendChild(g);return b}}});C.Base=new q({translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(b){this.viz=b;this.opt=b.config;this.size=false;this.createCanvas();this.translateToCenter()},createCanvas:function(){var b=this.opt,e=b.width,f=b.height;this.canvas=a("canvas",{id:b.injectInto+b.idSuffix,width:e,height:f,style:{position:"absolute",top:0,left:0,
width:e+"px",height:f+"px"}})},getCtx:function(){if(!this.ctx)return this.ctx=this.canvas.getContext("2d");return this.ctx},getSize:function(){if(this.size)return this.size;var b=this.canvas;return this.size={width:b.width,height:b.height}},translateToCenter:function(b){var e=this.getSize(),f=b?e.width-b.width-this.translateOffsetX*2:e.width;height=b?e.height-b.height-this.translateOffsetY*2:e.height;e=this.getCtx();b&&e.scale(1/this.scaleOffsetX,1/this.scaleOffsetY);e.translate(f/2,height/2)},resize:function(b,
e){var f=this.getSize(),g=this.canvas,i=g.style;this.size=false;g.width=b;g.height=e;i.width=b+"px";i.height=e+"px";c?this.translateToCenter():this.translateToCenter(f);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;this.clear();this.viz.resize(b,e,this)},translate:function(b,e,f){var g=this.scaleOffsetY;this.translateOffsetX+=b*this.scaleOffsetX;this.translateOffsetY+=e*g;this.getCtx().translate(b,e);!f&&this.plot()},scale:function(b,e,f){this.scaleOffsetX*=b;
this.scaleOffsetY*=e;this.getCtx().scale(b,e);!f&&this.plot()},clear:function(){var b=this.getSize(),e=this.translateOffsetX,f=this.translateOffsetY,g=this.scaleOffsetX,i=this.scaleOffsetY;this.getCtx().clearRect((-b.width/2-e)*1/g,(-b.height/2-f)*1/i,b.width*1/g,b.height*1/i)},plot:function(){this.clear();this.viz.plot(this)}});C.Background={};C.Background.Circles=new q({initialize:function(b,e){this.viz=b;this.config=h.merge({idSuffix:"-bkcanvas",levelDistance:100,numberOfCircles:6,CanvasStyles:{},
offset:0},e)},resize:function(b,e,f){this.plot(f)},plot:function(b){b=b.getCtx();var e=this.config,f=e.CanvasStyles;for(var g in f)b[g]=f[g];g=e.numberOfCircles;e=e.levelDistance;for(f=1;f<=g;f++){b.beginPath();b.arc(0,0,e*f,0,2*Math.PI,false);b.stroke();b.closePath()}}})})();var z=function(a,d){this.theta=a;this.rho=d};$jit.Polar=z;z.prototype={getc:function(a){return this.toComplex(a)},getp:function(){return this},set:function(a){a=a.getp();this.theta=a.theta;this.rho=a.rho},setc:function(a,d){this.rho=
Math.sqrt(a*a+d*d);this.theta=Math.atan2(d,a);if(this.theta<0)this.theta+=Math.PI*2},setp:function(a,d){this.theta=a;this.rho=d},clone:function(){return new z(this.theta,this.rho)},toComplex:function(a){var d=Math.cos(this.theta)*this.rho,c=Math.sin(this.theta)*this.rho;if(a)return{x:d,y:c};return new u(d,c)},add:function(a){return new z(this.theta+a.theta,this.rho+a.rho)},scale:function(a){return new z(this.theta,this.rho*a)},equals:function(a){return this.theta==a.theta&&this.rho==a.rho},$add:function(a){this.theta+=
a.theta;this.rho+=a.rho;return this},$madd:function(a){this.theta=(this.theta+a.theta)%(Math.PI*2);this.rho+=a.rho;return this},$scale:function(a){this.rho*=a;return this},interpolate:function(a,d){var c=Math.PI,b=c*2,e=function(j){return j<0?j%b+b:j%b},f=this.theta,g=a.theta,i=Math.abs(f-g);return{theta:i==c?f>g?e(g+(f-b-g)*d):e(g-b+(f-g)*d):i>=c?f>g?e(g+(f-b-g)*d):e(g-b+(f-(g-b))*d):e(g+(f-g)*d),rho:(this.rho-a.rho)*d+a.rho}}};z.KER=new z(0,0);var u=function(a,d){this.x=a;this.y=d};$jit.Complex=
u;u.prototype={getc:function(){return this},getp:function(a){return this.toPolar(a)},set:function(a){a=a.getc(true);this.x=a.x;this.y=a.y},setc:function(a,d){this.x=a;this.y=d},setp:function(a,d){this.x=Math.cos(a)*d;this.y=Math.sin(a)*d},clone:function(){return new u(this.x,this.y)},toPolar:function(a){var d=this.norm(),c=Math.atan2(this.y,this.x);if(c<0)c+=Math.PI*2;if(a)return{theta:c,rho:d};return new z(c,d)},norm:function(){return Math.sqrt(this.squaredNorm())},squaredNorm:function(){return this.x*
this.x+this.y*this.y},add:function(a){return new u(this.x+a.x,this.y+a.y)},prod:function(a){return new u(this.x*a.x-this.y*a.y,this.y*a.x+this.x*a.y)},conjugate:function(){return new u(this.x,-this.y)},scale:function(a){return new u(this.x*a,this.y*a)},equals:function(a){return this.x==a.x&&this.y==a.y},$add:function(a){this.x+=a.x;this.y+=a.y;return this},$prod:function(a){var d=this.x,c=this.y;this.x=d*a.x-c*a.y;this.y=c*a.x+d*a.y;return this},$conjugate:function(){this.y=-this.y;return this},$scale:function(a){this.x*=
a;this.y*=a;return this},$div:function(a){var d=this.x,c=this.y,b=a.squaredNorm();this.x=d*a.x+c*a.y;this.y=c*a.x-d*a.y;return this.$scale(1/b)}};u.KER=new u(0,0);$jit.Graph=new q({initialize:function(a,d,c,b){this.Node=d;this.Edge=c;this.Label=b;this.opt=h.merge({complex:false,Node:{}},a||{});this.nodes={};this.edges={};var e=this;this.nodeList={};for(var f in L)e.nodeList[f]=function(g){return function(){var i=Array.prototype.slice.call(arguments);e.eachNode(function(j){j[g].apply(j,i)})}}(f)},
getNode:function(a){if(this.hasNode(a))return this.nodes[a];return false},getByName:function(a){for(var d in this.nodes){var c=this.nodes[d];if(c.name==a)return c}return false},getAdjacence:function(a,d){if(a in this.edges)return this.edges[a][d];return false},addNode:function(a){if(!this.nodes[a.id]){var d=this.edges[a.id]={};this.nodes[a.id]=new r.Node(h.extend({id:a.id,name:a.name,data:h.merge(a.data||{},{}),adjacencies:d},this.opt.Node),this.opt.complex,this.Node,this.Edge,this.Label)}return this.nodes[a.id]},
addAdjacence:function(a,d,c){this.hasNode(a.id)||this.addNode(a);this.hasNode(d.id)||this.addNode(d);a=this.nodes[a.id];d=this.nodes[d.id];if(!a.adjacentTo(d)){var b=this.edges[a.id]=this.edges[a.id]||{},e=this.edges[d.id]=this.edges[d.id]||{};b[d.id]=e[a.id]=new r.Adjacence(a,d,c,this.Edge,this.Label);return b[d.id]}return this.edges[a.id][d.id]},removeNode:function(a){if(this.hasNode(a)){delete this.nodes[a];var d=this.edges[a];for(var c in d)delete this.edges[c][a];delete this.edges[a]}},removeAdjacence:function(a,
d){delete this.edges[a][d];delete this.edges[d][a]},hasNode:function(a){return a in this.nodes},empty:function(){this.nodes={};this.edges={}}});var r=$jit.Graph,L;(function(){var a=function(b,e,f,g,i){var j;f=f||"current";b="$"+(b?b+"-":"");if(f=="current")j=this.data;else if(f=="start")j=this.startData;else if(f=="end")j=this.endData;b=b+e;if(g)return j[b];if(!this.Config.overridable)return i[e]||0;return b in j?j[b]:b in this.data?this.data[b]:i[e]||0},d=function(b,e,f,g){g=g||"current";b="$"+(b?
b+"-":"");var i;if(g=="current")i=this.data;else if(g=="start")i=this.startData;else if(g=="end")i=this.endData;i[b+e]=f},c=function(b,e){b="$"+(b?b+"-":"");var f=this;h.each(e,function(g){g=b+g;delete f.data[g];delete f.endData[g];delete f.startData[g]})};L={getData:function(b,e,f){return a.call(this,"",b,e,f,this.Config)},setData:function(b,e,f){d.call(this,"",b,e,f)},setDataset:function(b,e){b=h.splat(b);for(var f in e)for(var g=0,i=h.splat(e[f]),j=b.length;g<j;g++)this.setData(f,i[g],b[g])},removeData:function(){c.call(this,
"",Array.prototype.slice.call(arguments))},getCanvasStyle:function(b,e,f){return a.call(this,"canvas",b,e,f,this.Config.CanvasStyles)},setCanvasStyle:function(b,e,f){d.call(this,"canvas",b,e,f)},setCanvasStyles:function(b,e){b=h.splat(b);for(var f in e)for(var g=0,i=h.splat(e[f]),j=b.length;g<j;g++)this.setCanvasStyle(f,i[g],b[g])},removeCanvasStyle:function(){c.call(this,"canvas",Array.prototype.slice.call(arguments))},getLabelData:function(b,e,f){return a.call(this,"label",b,e,f,this.Label)},setLabelData:function(b,
e,f){d.call(this,"label",b,e,f)},setLabelDataset:function(b,e){b=h.splat(b);for(var f in e)for(var g=0,i=h.splat(e[f]),j=b.length;g<j;g++)this.setLabelData(f,i[g],b[g])},removeLabelData:function(){c.call(this,"label",Array.prototype.slice.call(arguments))}}})();r.Node=new q({initialize:function(a,d,c,b,e){d={id:"",name:"",data:{},startData:{},endData:{},adjacencies:{},selected:false,drawn:false,exist:false,angleSpan:{begin:0,end:0},pos:d&&new u(0,0)||new z(0,0),startPos:d&&new u(0,0)||new z(0,0),
endPos:d&&new u(0,0)||new z(0,0)};h.extend(this,h.extend(d,a));this.Config=this.Node=c;this.Edge=b;this.Label=e},adjacentTo:function(a){return a.id in this.adjacencies},getAdjacency:function(a){return this.adjacencies[a]},getPos:function(a){a=a||"current";if(a=="current")return this.pos;else if(a=="end")return this.endPos;else if(a=="start")return this.startPos},setPos:function(a,d){d=d||"current";var c;if(d=="current")c=this.pos;else if(d=="end")c=this.endPos;else if(d=="start")c=this.startPos;c.set(a)}});
r.Node.implement(L);r.Adjacence=new q({initialize:function(a,d,c,b,e){this.nodeFrom=a;this.nodeTo=d;this.data=c||{};this.startData={};this.endData={};this.Config=this.Edge=b;this.Label=e}});r.Adjacence.implement(L);r.Util={filter:function(a){if(!a||h.type(a)!="string")return function(){return true};var d=a.split(" ");return function(c){for(var b=0;b<d.length;b++)if(c[d[b]])return false;return true}},getNode:function(a,d){return a.nodes[d]},eachNode:function(a,d,c){c=this.filter(c);for(var b in a.nodes)c(a.nodes[b])&&
d(a.nodes[b])},eachAdjacency:function(a,d,c){var b=a.adjacencies;c=this.filter(c);for(var e in b){var f=b[e];if(c(f)){if(f.nodeFrom!=a){var g=f.nodeFrom;f.nodeFrom=f.nodeTo;f.nodeTo=g}d(f,e)}}},computeLevels:function(a,d,c,b){c=c||0;var e=this.filter(b);this.eachNode(a,function(i){i._flag=false;i._depth=-1},b);a=a.getNode(d);a._depth=c;for(var f=[a];f.length!=0;){var g=f.pop();g._flag=true;this.eachAdjacency(g,function(i){i=i.nodeTo;if(i._flag==false&&e(i)){if(i._depth<0)i._depth=g._depth+1+c;f.unshift(i)}},
b)}},eachBFS:function(a,d,c,b){var e=this.filter(b);this.clean(a);for(var f=[a.getNode(d)];f.length!=0;){a=f.pop();a._flag=true;c(a,a._depth);this.eachAdjacency(a,function(g){g=g.nodeTo;if(g._flag==false&&e(g)){g._flag=true;f.unshift(g)}},b)}},eachLevel:function(a,d,c,b,e){var f=a._depth,g=this.filter(e),i=this;c=c===false?Number.MAX_VALUE-f:c;(function j(k,l,n){var m=k._depth;m>=l&&m<=n&&g(k)&&b(k,m);m<n&&i.eachAdjacency(k,function(o){o=o.nodeTo;o._depth>m&&j(o,l,n)})})(a,d+f,c+f)},eachSubgraph:function(a,
d,c){this.eachLevel(a,0,false,d,c)},eachSubnode:function(a,d,c){this.eachLevel(a,1,1,d,c)},anySubnode:function(a,d,c){var b=false;d=d||h.lambda(true);var e=h.type(d)=="string"?function(f){return f[d]}:d;this.eachSubnode(a,function(f){if(e(f))b=true},c);return b},getSubnodes:function(a,d,c){var b=[];d=d||0;var e;if(h.type(d)=="array"){e=d[0];d=d[1]}else{e=d;d=Number.MAX_VALUE-a._depth}this.eachLevel(a,e,d,function(f){b.push(f)},c);return b},getParents:function(a){var d=[];this.eachAdjacency(a,function(c){c=
c.nodeTo;c._depth<a._depth&&d.push(c)});return d},isDescendantOf:function(a,d){if(a.id==d)return true;for(var c=this.getParents(a),b=false,e=0;!b&&e<c.length;e++)b=b||this.isDescendantOf(c[e],d);return b},clean:function(a){this.eachNode(a,function(d){d._flag=false})},getClosestNodeToOrigin:function(a,d,c){return this.getClosestNodeToPos(a,z.KER,d,c)},getClosestNodeToPos:function(a,d,c,b){var e=null;c=c||"current";d=d&&d.getc(true)||u.KER;var f=function(g,i){var j=g.x-i.x,k=g.y-i.y;return j*j+k*k};
this.eachNode(a,function(g){e=e==null||f(g.getPos(c).getc(true),d)<f(e.getPos(c).getc(true),d)?g:e},b);return e}};h.each(["getNode","eachNode","computeLevels","eachBFS","clean","getClosestNodeToPos","getClosestNodeToOrigin"],function(a){r.prototype[a]=function(){return r.Util[a].apply(r.Util,[this].concat(Array.prototype.slice.call(arguments)))}});h.each(["eachAdjacency","eachLevel","eachSubgraph","eachSubnode","anySubnode","getSubnodes","getParents","isDescendantOf"],function(a){r.Node.prototype[a]=
function(){return r.Util[a].apply(r.Util,[this].concat(Array.prototype.slice.call(arguments)))}});r.Op={options:{type:"nothing",duration:2E3,hideLabels:true,fps:30},initialize:function(a){this.viz=a},removeNode:function(a,d){var c=this.viz,b=h.merge(this.options,c.controller,d),e=h.splat(a),f,g,i;switch(b.type){case "nothing":for(f=0;f<e.length;f++)c.graph.removeNode(e[f]);break;case "replot":this.removeNode(e,{type:"nothing"});c.labels.clearLabels();c.refresh(true);break;case "fade:seq":case "fade":g=
this;for(f=0;f<e.length;f++){i=c.graph.getNode(e[f]);i.setData("alpha",0,"end")}c.fx.animate(h.merge(b,{modes:["node-property:alpha"],onComplete:function(){g.removeNode(e,{type:"nothing"});c.labels.clearLabels();c.reposition();c.fx.animate(h.merge(b,{modes:["linear"]}))}}));break;case "fade:con":g=this;for(f=0;f<e.length;f++){i=c.graph.getNode(e[f]);i.setData("alpha",0,"end");i.ignore=true}c.reposition();c.fx.animate(h.merge(b,{modes:["node-property:alpha","linear"],onComplete:function(){g.removeNode(e,
{type:"nothing"})}}));break;case "iter":g=this;c.fx.sequence({condition:function(){return e.length!=0},step:function(){g.removeNode(e.shift(),{type:"nothing"});c.labels.clearLabels()},onComplete:function(){b.onComplete()},duration:Math.ceil(b.duration/e.length)});break;default:this.doError()}},removeEdge:function(a,d){var c=this.viz,b=h.merge(this.options,c.controller,d),e=h.type(a[0])=="string"?[a]:a,f,g,i;switch(b.type){case "nothing":for(f=0;f<e.length;f++)c.graph.removeAdjacence(e[f][0],e[f][1]);
break;case "replot":this.removeEdge(e,{type:"nothing"});c.refresh(true);break;case "fade:seq":case "fade":g=this;for(f=0;f<e.length;f++)(i=c.graph.getAdjacence(e[f][0],e[f][1]))&&i.setData("alpha",0,"end");c.fx.animate(h.merge(b,{modes:["edge-property:alpha"],onComplete:function(){g.removeEdge(e,{type:"nothing"});c.reposition();c.fx.animate(h.merge(b,{modes:["linear"]}))}}));break;case "fade:con":g=this;for(f=0;f<e.length;f++)if(i=c.graph.getAdjacence(e[f][0],e[f][1])){i.setData("alpha",0,"end");
i.ignore=true}c.reposition();c.fx.animate(h.merge(b,{modes:["edge-property:alpha","linear"],onComplete:function(){g.removeEdge(e,{type:"nothing"})}}));break;case "iter":g=this;c.fx.sequence({condition:function(){return e.length!=0},step:function(){g.removeEdge(e.shift(),{type:"nothing"});c.labels.clearLabels()},onComplete:function(){b.onComplete()},duration:Math.ceil(b.duration/e.length)});break;default:this.doError()}},sum:function(a,d){var c=this.viz,b=h.merge(this.options,c.controller,d),e=c.root,
f;c.root=d.id||c.root;switch(b.type){case "nothing":f=c.construct(a);f.eachNode(function(i){i.eachAdjacency(function(j){c.graph.addAdjacence(j.nodeFrom,j.nodeTo,j.data)})});break;case "replot":c.refresh(true);this.sum(a,{type:"nothing"});c.refresh(true);break;case "fade:seq":case "fade":case "fade:con":that=this;f=c.construct(a);var g=!this.preprocessSum(f)?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];c.reposition();if(b.type!="fade:con")c.fx.animate(h.merge(b,{modes:["linear"],
onComplete:function(){c.fx.animate(h.merge(b,{modes:g,onComplete:function(){b.onComplete()}}))}}));else{c.graph.eachNode(function(i){if(i.id!=e&&i.pos.getp().equals(z.KER)){i.pos.set(i.endPos);i.startPos.set(i.endPos)}});c.fx.animate(h.merge(b,{modes:["linear"].concat(g)}))}break;default:this.doError()}},morph:function(a,d,c){var b=this.viz,e=h.merge(this.options,b.controller,d),f=b.root,g;b.root=d.id||b.root;switch(e.type){case "nothing":g=b.construct(a);g.eachNode(function(k){var l=b.graph.hasNode(k.id);
k.eachAdjacency(function(m){var o=!!b.graph.getAdjacence(m.nodeFrom.id,m.nodeTo.id);b.graph.addAdjacence(m.nodeFrom,m.nodeTo,m.data);if(o){o=b.graph.getAdjacence(m.nodeFrom.id,m.nodeTo.id);for(var p in m.data||{})o.data[p]=m.data[p]}});if(l){l=b.graph.getNode(k.id);for(var n in k.data||{})l.data[n]=k.data[n]}});b.graph.eachNode(function(k){k.eachAdjacency(function(l){g.getAdjacence(l.nodeFrom.id,l.nodeTo.id)||b.graph.removeAdjacence(l.nodeFrom.id,l.nodeTo.id)});g.hasNode(k.id)||b.graph.removeNode(k.id)});
break;case "replot":b.labels.clearLabels(true);this.morph(a,{type:"nothing"});b.refresh(true);b.refresh(true);break;case "fade:seq":case "fade":case "fade:con":that=this;g=b.construct(a);var i=c&&"node-property"in c&&h.map(h.splat(c["node-property"]),function(k){return"$"+k});b.graph.eachNode(function(k){var l=g.getNode(k.id);if(l){l=l.data;for(var n in l)if(i&&h.indexOf(i,n)>-1)k.endData[n]=l[n];else k.data[n]=l[n]}else{k.setData("alpha",1);k.setData("alpha",1,"start");k.setData("alpha",0,"end");
k.ignore=true}});b.graph.eachNode(function(k){k.ignore||k.eachAdjacency(function(l){if(!(l.nodeFrom.ignore||l.nodeTo.ignore)){var n=g.getNode(l.nodeFrom.id);l=g.getNode(l.nodeTo.id);if(!n.adjacentTo(l)){l=b.graph.getAdjacence(n.id,l.id);j=true;l.setData("alpha",1);l.setData("alpha",1,"start");l.setData("alpha",0,"end")}}})});var j=this.preprocessSum(g);a=!j?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];a[0]+=c&&"node-property"in c?":"+h.splat(c["node-property"]).join(":"):
"";a[1]=(a[1]||"edge-property:alpha")+(c&&"edge-property"in c?":"+h.splat(c["edge-property"]).join(":"):"");c&&"label-property"in c&&a.push("label-property:"+h.splat(c["label-property"]).join(":"));b.reposition();b.graph.eachNode(function(k){if(k.id!=f&&k.pos.getp().equals(z.KER)){k.pos.set(k.endPos);k.startPos.set(k.endPos)}});b.fx.animate(h.merge(e,{modes:["polar"].concat(a),onComplete:function(){b.graph.eachNode(function(k){k.ignore&&b.graph.removeNode(k.id)});b.graph.eachNode(function(k){k.eachAdjacency(function(l){l.ignore&&
b.graph.removeAdjacence(l.nodeFrom.id,l.nodeTo.id)})});e.onComplete()}}));break;default:}},contract:function(a,d){var c=this.viz;if(!(a.collapsed||!a.anySubnode(h.lambda(true)))){d=h.merge(this.options,c.config,d||{},{modes:["node-property:alpha:span","linear"]});a.collapsed=true;(function b(e){e.eachSubnode(function(f){f.ignore=true;f.setData("alpha",0,d.type=="animate"?"end":"current");b(f)})})(a);if(d.type=="animate"){c.compute("end");c.rotated&&c.rotate(c.rotated,"none",{property:"end"});(function b(e){e.eachSubnode(function(f){f.setPos(a.getPos("end"),
"end");b(f)})})(a);c.fx.animate(d)}else d.type=="replot"&&c.refresh()}},expand:function(a,d){if("collapsed"in a){var c=this.viz;d=h.merge(this.options,c.config,d||{},{modes:["node-property:alpha:span","linear"]});delete a.collapsed;(function b(e){e.eachSubnode(function(f){delete f.ignore;f.setData("alpha",1,d.type=="animate"?"end":"current");b(f)})})(a);if(d.type=="animate"){c.compute("end");c.rotated&&c.rotate(c.rotated,"none",{property:"end"});c.fx.animate(d)}else d.type=="replot"&&c.refresh()}},
preprocessSum:function(a){var d=this.viz;a.eachNode(function(b){if(!d.graph.hasNode(b.id)){d.graph.addNode(b);b=d.graph.getNode(b.id);b.setData("alpha",0);b.setData("alpha",0,"start");b.setData("alpha",1,"end")}});var c=false;a.eachNode(function(b){b.eachAdjacency(function(e){var f=d.graph.getNode(e.nodeFrom.id),g=d.graph.getNode(e.nodeTo.id);if(!f.adjacentTo(g)){e=d.graph.addAdjacence(f,g,e.data);if(f.startAlpha==f.endAlpha&&g.startAlpha==g.endAlpha){c=true;e.setData("alpha",0);e.setData("alpha",
0,"start");e.setData("alpha",1,"end")}}})});return c}};var P={none:{render:h.empty,contains:h.lambda(false)},circle:{render:function(a,d,c,b){b=b.getCtx();b.beginPath();b.arc(d.x,d.y,c,0,Math.PI*2,true);b.closePath();b[a]()},contains:function(a,d,c){var b=a.x-d.x;a=a.y-d.y;return b*b+a*a<=c*c}},ellipse:{render:function(a,d,c,b,e){e=e.getCtx();b/=2;c/=2;e.save();e.scale(c/b,b/c);e.beginPath();e.arc(d.x*(b/c),d.y*(c/b),b,0,Math.PI*2,true);e.closePath();e[a]();e.restore()},contains:function(a,d,c,b){c/=
2;b/=2;c=(c+b)/2;b=a.x-d.x;a=a.y-d.y;return b*b+a*a<=c*c}},square:{render:function(a,d,c,b){b.getCtx()[a+"Rect"](d.x-c,d.y-c,2*c,2*c)},contains:function(a,d,c){return Math.abs(d.x-a.x)<=c&&Math.abs(d.y-a.y)<=c}},rectangle:{render:function(a,d,c,b,e){e.getCtx()[a+"Rect"](d.x-c/2,d.y-b/2,c,b)},contains:function(a,d,c,b){return Math.abs(d.x-a.x)<=c/2&&Math.abs(d.y-a.y)<=b/2}},triangle:{render:function(a,d,c,b){b=b.getCtx();var e=d.x,f=d.y-c,g=e-c;d=d.y+c;c=e+c;b.beginPath();b.moveTo(e,f);b.lineTo(g,
d);b.lineTo(c,d);b.closePath();b[a]()},contains:function(a,d,c){return P.circle.contains(a,d,c)}},star:{render:function(a,d,c,b){b=b.getCtx();var e=Math.PI/5;b.save();b.translate(d.x,d.y);b.beginPath();b.moveTo(c,0);for(d=0;d<9;d++){b.rotate(e);d%2==0?b.lineTo(c/0.525731*0.200811,0):b.lineTo(c,0)}b.closePath();b[a]();b.restore()},contains:function(a,d,c){return P.circle.contains(a,d,c)}}},U={line:{render:function(a,d,c){c=c.getCtx();c.beginPath();c.moveTo(a.x,a.y);c.lineTo(d.x,d.y);c.stroke()},contains:function(a,
d,c,b){var e=Math.min,f=Math.max,g=e(a.x,d.x),i=f(a.x,d.x);e=e(a.y,d.y);f=f(a.y,d.y);if(c.x>=g&&c.x<=i&&c.y>=e&&c.y<=f){if(Math.abs(d.x-a.x)<=b)return true;return Math.abs((d.y-a.y)/(d.x-a.x)*(c.x-a.x)+a.y-c.y)<=b}return false}},arrow:{render:function(a,d,c,b,e){e=e.getCtx();if(b){b=a;a=d;d=b}b=new u(d.x-a.x,d.y-a.y);b.$scale(c/b.norm());c=new u(d.x-b.x,d.y-b.y);var f=new u(-b.y/2,b.x/2);b=c.add(f);c=c.$add(f.$scale(-1));e.beginPath();e.moveTo(a.x,a.y);e.lineTo(d.x,d.y);e.stroke();e.beginPath();e.moveTo(b.x,
b.y);e.lineTo(c.x,c.y);e.lineTo(d.x,d.y);e.closePath();e.fill()},contains:function(a,d,c,b){return U.line.contains(a,d,c,b)}},hyperline:{render:function(a,d,c,b){function e(g,i){return g<i?g+Math.PI>i?false:true:i+Math.PI>g?true:false}b=b.getCtx();var f=function(g,i){var j=g.x*i.y-g.y*i.x,k=g.squaredNorm(),l=i.squaredNorm();if(j==0)return{x:0,y:0,ratio:-1};var n=(g.y*l-i.y*k+g.y-i.y)/j;j=(i.x*k-g.x*l+i.x-g.x)/j;k=-n/2;l=-j/2;var m=(n*n+j*j)/4-1;if(m<0)return{x:0,y:0,ratio:-1};m=Math.sqrt(m);return{x:k,
y:l,ratio:m>1E3?-1:m,a:n,b:j}}(a,d);if(f.a>1E3||f.b>1E3||f.ratio<0){b.beginPath();b.moveTo(a.x*c,a.y*c);b.lineTo(d.x*c,d.y*c)}else{d=Math.atan2(d.y-f.y,d.x-f.x);a=Math.atan2(a.y-f.y,a.x-f.x);e=e(d,a);b.beginPath();b.arc(f.x*c,f.y*c,f.ratio*c,d,a,e)}b.stroke()},contains:h.lambda(false)}};r.Plot={initialize:function(a,d){this.viz=a;this.config=a.config;this.node=a.config.Node;this.edge=a.config.Edge;this.animation=new O;this.nodeTypes=new d.Plot.NodeTypes;this.edgeTypes=new d.Plot.EdgeTypes;this.labels=
a.labels},nodeHelper:P,edgeHelper:U,Interpolator:{map:{border:"color",color:"color",width:"number",height:"number",dim:"number",alpha:"number",lineWidth:"number",angularWidth:"number",span:"number",valueArray:"array-number",dimArray:"array-number"},canvas:{globalAlpha:"number",fillStyle:"color",strokeStyle:"color",lineWidth:"number",shadowBlur:"number",shadowColor:"color",shadowOffsetX:"number",shadowOffsetY:"number",miterLimit:"number"},label:{size:"number",color:"color"},compute:function(a,d,c){return a+
(d-a)*c},moebius:function(a,d,c,b){d=b.scale(-c);if(d.norm()<1){c=d.x;b=d.y;var e=a.startPos.getc().moebiusTransformation(d);a.pos.setc(e.x,e.y);d.x=c;d.y=b}},linear:function(a,d,c){d=a.startPos.getc(true);var b=a.endPos.getc(true);a.pos.setc(this.compute(d.x,b.x,c),this.compute(d.y,b.y,c))},polar:function(a,d,c){d=a.startPos.getp(true);c=a.endPos.getp().interpolate(d,c);a.pos.setp(c.theta,c.rho)},number:function(a,d,c,b,e){var f=a[b](d,"start");b=a[b](d,"end");a[e](d,this.compute(f,b,c))},color:function(a,
d,c,b,e){var f=h.hexToRgb(a[b](d,"start"));b=h.hexToRgb(a[b](d,"end"));var g=this.compute;c=h.rgbToHex([parseInt(g(f[0],b[0],c)),parseInt(g(f[1],b[1],c)),parseInt(g(f[2],b[2],c))]);a[e](d,c)},"array-number":function(a,d,c,b,e){var f=a[b](d,"start");b=a[b](d,"end");for(var g=[],i=0,j=f.length;i<j;i++){var k=f[i],l=b[i];if(k.length){for(var n=0,m=k.length,o=[];n<m;n++)o.push(this.compute(k[n],l[n],c));g.push(o)}else g.push(this.compute(k,l,c))}a[e](d,g)},node:function(a,d,c,b,e,f){b=this[b];if(d)for(var g=
d.length,i=0;i<g;i++){var j=d[i];this[b[j]](a,j,c,e,f)}else for(j in b)this[b[j]](a,j,c,e,f)},edge:function(a,d,c,b,e,f){a=a.adjacencies;for(var g in a)this.node(a[g],d,c,b,e,f)},"node-property":function(a,d,c){this.node(a,d,c,"map","getData","setData")},"edge-property":function(a,d,c){this.edge(a,d,c,"map","getData","setData")},"label-property":function(a,d,c){this.node(a,d,c,"label","getLabelData","setLabelData")},"node-style":function(a,d,c){this.node(a,d,c,"canvas","getCanvasStyle","setCanvasStyle")},
"edge-style":function(a,d,c){this.edge(a,d,c,"canvas","getCanvasStyle","setCanvasStyle")}},sequence:function(a){var d=this;a=h.merge({condition:h.lambda(false),step:h.empty,onComplete:h.empty,duration:200},a||{});var c=setInterval(function(){if(a.condition())a.step();else{clearInterval(c);a.onComplete()}d.viz.refresh(true)},a.duration)},prepare:function(a){var d=this.viz.graph,c={"node-property":{getter:"getData",setter:"setData"},"edge-property":{getter:"getData",setter:"setData"},"node-style":{getter:"getCanvasStyle",
setter:"setCanvasStyle"},"edge-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"}},b={};if(h.type(a)=="array")for(var e=0,f=a.length;e<f;e++){var g=a[e].split(":");b[g.shift()]=g}else for(e in a)if(e=="position")b[a.position]=[];else b[e]=h.splat(a[e]);d.eachNode(function(i){i.startPos.set(i.pos);h.each(["node-property","node-style"],function(j){if(j in b)for(var k=b[j],l=0,n=k.length;l<n;l++)i[c[j].setter](k[l],i[c[j].getter](k[l]),"start")});h.each(["edge-property","edge-style"],function(j){if(j in
b){var k=b[j];i.eachAdjacency(function(l){for(var n=0,m=k.length;n<m;n++)l[c[j].setter](k[n],l[c[j].getter](k[n]),"start")})}})});return b},animate:function(a,d){a=h.merge(this.viz.config,a||{});var c=this,b=this.viz.graph,e=this.Interpolator,f=a.type==="nodefx"?this.nodeFxAnimation:this.animation,g=this.prepare(a.modes);a.hideLabels&&this.labels.hideLabels(true);f.setOptions(h.merge(a,{$animating:false,compute:function(i){b.eachNode(function(j){for(var k in g)e[k](j,g[k],i,d)});c.plot(a,this.$animating,
i);this.$animating=true},complete:function(){a.hideLabels&&c.labels.hideLabels(false);c.plot(a);a.onComplete();a.onAfterCompute()}})).start()},nodeFx:function(a){var d=this.viz,c=d.graph,b=this.nodeFxAnimation,e=h.merge(this.viz.config,{elements:{id:false,properties:{}},reposition:false});a=h.merge(e,a||{},{onBeforeCompute:h.empty,onAfterCompute:h.empty});b.stopTimer();var f=a.elements.properties;if(a.elements.id){b=h.splat(a.elements.id);h.each(b,function(i){if(i=c.getNode(i))for(var j in f)i.setData(j,
f[j],"end")})}else c.eachNode(function(i){for(var j in f)i.setData(j,f[j],"end")});b=[];for(var g in f)b.push(g);g=["node-property:"+b.join(":")];if(a.reposition){g.push("linear");d.compute("end")}this.animate(h.merge(a,{modes:g,type:"nodefx"}))},plot:function(a,d){var c=this.viz,b=c.graph,e=c.canvas;c=c.root;var f=this,g=e.getCtx(),i=Math.min;a=a||this.viz.controller;a.clearCanvas&&e.clear();if(c=b.getNode(c)){var j=!!c.visited;b.eachNode(function(k){var l=k.getData("alpha");k.eachAdjacency(function(n){var m=
n.nodeTo;if(!!m.visited===j&&k.drawn&&m.drawn){!d&&a.onBeforePlotLine(n);g.save();g.globalAlpha=i(l,m.getData("alpha"),n.getData("alpha"));f.plotLine(n,e,d);g.restore();!d&&a.onAfterPlotLine(n)}});g.save();if(k.drawn){!d&&a.onBeforePlotNode(k);f.plotNode(k,e,d);!d&&a.onAfterPlotNode(k)}if(!f.labelsHidden&&a.withLabels)k.drawn&&l>=0.95?f.labels.plotLabel(e,k,a):f.labels.hideLabel(k,false);g.restore();k.visited=!j})}},plotTree:function(a,d,c){var b=this,e=this.viz.canvas,f=e.getCtx(),g=a.getData("alpha");
a.eachSubnode(function(i){if(d.plotSubtree(a,i)&&i.exist&&i.drawn){var j=a.getAdjacency(i.id);!c&&d.onBeforePlotLine(j);f.globalAlpha=Math.min(g,i.getData("alpha"));b.plotLine(j,e,c);!c&&d.onAfterPlotLine(j);b.plotTree(i,d,c)}});if(a.drawn){!c&&d.onBeforePlotNode(a);this.plotNode(a,e,c);!c&&d.onAfterPlotNode(a);!d.hideLabels&&d.withLabels&&g>=0.95?this.labels.plotLabel(e,a,d):this.labels.hideLabel(a,false)}else this.labels.hideLabel(a,true)},plotNode:function(a,d,c){var b=a.getData("type"),e=this.node.CanvasStyles;
if(b!="none"){var f=a.getData("lineWidth"),g=a.getData("color"),i=a.getData("alpha"),j=d.getCtx();j.lineWidth=f;j.fillStyle=j.strokeStyle=g;j.globalAlpha=i;for(var k in e)j[k]=a.getCanvasStyle(k);this.nodeTypes[b].render.call(this,a,d,c)}},plotLine:function(a,d,c){var b=a.getData("type"),e=this.edge.CanvasStyles;if(b!="none"){var f=a.getData("lineWidth"),g=a.getData("color"),i=d.getCtx();i.lineWidth=f;i.fillStyle=i.strokeStyle=g;for(var j in e)i[j]=a.getCanvasStyle(j);this.edgeTypes[b].render.call(this,
a,d,c)}}};r.Label={};r.Label.Native=new q({plotLabel:function(a,d,c){var b=a.getCtx();d.pos.getc(true);b.font=d.getLabelData("style")+" "+d.getLabelData("size")+"px "+d.getLabelData("family");b.textAlign=d.getLabelData("textAlign");b.fillStyle=b.strokeStyle=d.getLabelData("color");b.textBaseline=d.getLabelData("textBaseline");this.renderLabel(a,d,c)},renderLabel:function(a,d){var c=a.getCtx(),b=d.pos.getc(true);c.fillText(d.name,b.x,b.y+d.getData("height")/2)},hideLabel:h.empty,hideLabels:h.empty});
r.Label.DOM=new q({labelsHidden:false,labelContainer:false,labels:{},getLabelContainer:function(){return this.labelContainer?this.labelContainer:this.labelContainer=document.getElementById(this.viz.config.labelContainer)},getLabel:function(a){return a in this.labels&&this.labels[a]!=null?this.labels[a]:this.labels[a]=document.getElementById(a)},hideLabels:function(a){this.getLabelContainer().style.display=a?"none":"";this.labelsHidden=a},clearLabels:function(a){for(var d in this.labels)if(a||!this.viz.graph.hasNode(d)){this.disposeLabel(d);
delete this.labels[d]}},disposeLabel:function(a){(a=this.getLabel(a))&&a.parentNode&&a.parentNode.removeChild(a)},hideLabel:function(a,d){a=h.splat(a);var c=d?"":"none",b=this;h.each(a,function(e){if(e=b.getLabel(e.id))e.style.display=c})},fitsInCanvas:function(a,d){var c=d.getSize();if(a.x>=c.width||a.x<0||a.y>=c.height||a.y<0)return false;return true}});r.Label.HTML=new q({Implements:r.Label.DOM,plotLabel:function(a,d,c){a=d.id;var b=this.getLabel(a);if(!b&&!(b=document.getElementById(a))){b=document.createElement("div");
var e=this.getLabelContainer();b.id=a;b.className="node";b.style.position="absolute";c.onCreateLabel(b,d);e.appendChild(b);this.labels[d.id]=b}this.placeLabel(b,d,c)}});r.Label.SVG=new q({Implements:r.Label.DOM,plotLabel:function(a,d,c){a=d.id;var b=this.getLabel(a);if(!b&&!(b=document.getElementById(a))){b=document.createElementNS("http://www.w3.org/2000/svg","svg:text");var e=document.createElementNS("http://www.w3.org/2000/svg","svg:tspan");b.appendChild(e);e=this.getLabelContainer();b.setAttribute("id",
a);b.setAttribute("class","node");e.appendChild(b);c.onCreateLabel(b,d);this.labels[d.id]=b}this.placeLabel(b,d,c)}});r.Geom=new q({initialize:function(a){this.viz=a;this.config=a.config;this.node=a.config.Node;this.edge=a.config.Edge},translate:function(a,d){d=h.splat(d);this.viz.graph.eachNode(function(c){h.each(d,function(b){c.getPos(b).$add(a)})})},setRightLevelToShow:function(a,d,c){var b=this.getRightLevelToShow(a,d),e=this.viz.labels,f=h.merge({execShow:true,execHide:true,onHide:h.empty,onShow:h.empty},
c||{});a.eachLevel(0,this.config.levelsToShow,function(g){if(g._depth-a._depth>b){f.onHide(g);if(f.execHide){g.drawn=false;g.exist=false;e.hideLabel(g,false)}}else{f.onShow(g);if(f.execShow)g.exist=true}});a.drawn=true},getRightLevelToShow:function(a,d){var c=this.config,b=c.levelsToShow;if(!c.constrained)return b;for(;!this.treeFitsInCanvas(a,d,b)&&b>1;)b--;return b}});var Z={construct:function(a){var d=h.type(a)=="array",c=new r(this.graphOptions,this.config.Node,this.config.Edge,this.config.Label);
d?function(b,e){for(var f=function(o){for(var p=0,s=e.length;p<s;p++)if(e[p].id==o)return e[p];return b.addNode({id:o,name:o})},g=0,i=e.length;g<i;g++){b.addNode(e[g]);var j=e[g].adjacencies;if(j)for(var k=0,l=j.length;k<l;k++){var n=j[k],m={};if(typeof j[k]!="string"){m=h.merge(n.data,{});n=n.nodeTo}b.addAdjacence(e[g],f(n),m)}}}(c,a):function(b,e){b.addNode(e);if(e.children)for(var f=0,g=e.children;f<g.length;f++){b.addAdjacence(e,g[f]);arguments.callee(b,g[f])}}(c,a);return c},loadJSON:function(a,
d){this.json=a;this.labels&&this.labels.clearLabels&&this.labels.clearLabels(true);this.graph=this.construct(a);this.root=h.type(a)!="array"?a.id:a[d?d:0].id},toJSON:function(a){a=a||"tree";if(a=="tree"){var d={};d=function b(e){var f={};f.id=e.id;f.name=e.name;f.data=e.data;var g=[];e.eachSubnode(function(i){g.push(b(i))});f.children=g;return f}(this.graph.getNode(this.root))}else{d=[];var c=!!this.graph.getNode(this.root).visited;this.graph.eachNode(function(b){var e={};e.id=b.id;e.name=b.name;
e.data=b.data;var f=[];b.eachAdjacency(function(g){var i=g.nodeTo;if(!!i.visited===c){var j={};j.nodeTo=i.id;j.data=g.data;f.push(j)}});e.adjacencies=f;d.push(e);b.visited=!c})}return d}},V=$jit.Layouts={},$={label:null,compute:function(a,d,c){this.initializeLabel(c);var b=this.label,e=b.style;a.eachNode(function(f){var g=f.getData("autoWidth"),i=f.getData("autoHeight");if(g||i){delete f.data.$width;delete f.data.$height;delete f.data.$dim;var j=f.getData("width"),k=f.getData("height");e.width=g?
"auto":j+"px";e.height=i?"auto":k+"px";b.innerHTML=f.name;g=b.offsetWidth;i=b.offsetHeight;j=f.getData("type");if(h.indexOf(["circle","square","triangle","star"],j)===-1){f.setData("width",g);f.setData("height",i)}else{g=g>i?g:i;f.setData("width",g);f.setData("height",g);f.setData("dim",g)}}})},initializeLabel:function(a){if(!this.label){this.label=document.createElement("div");document.body.appendChild(this.label)}this.setLabelStyles(a)},setLabelStyles:function(){h.extend(this.label.style,{visibility:"hidden",
position:"absolute",width:"auto",height:"auto"});this.label.className="jit-autoadjust-label"}};V.Tree=function(){function a(n,m,o,p,s){var t=m.Node,x=m.multitree;if(t.overridable){var v=-1,w=-1;n.eachNode(function(y){if(y._depth==o&&(!x||"$orn"in y.data&&y.data.$orn==p)){var F=y.getData("width",s);y=y.getData("height",s);v=v<F?F:v;w=w<y?y:w}});return{width:v<0?t.width:v,height:w<0?t.height:w}}else return t}function d(n,m,o,p){p=p=="left"||p=="right"?"y":"x";n.getPos(m)[p]+=o}function c(n,m){var o=
[];h.each(n,function(p){p=l.call(p);p[0]+=m;p[1]+=m;o.push(p)});return o}function b(n,m){if(n.length==0)return m;if(m.length==0)return n;var o=n.shift(),p=m.shift();return[[o[0],p[1]]].concat(b(n,m))}function e(n,m){m=m||[];if(n.length==0)return m;var o=n.pop();return e(n,b(o,m))}function f(n,m,o,p,s){if(n.length<=s||m.length<=s)return 0;var t=n[s][1],x=m[s][0];return Math.max(f(n,m,o,p,++s)+o,t-x+p)}function g(n,m,o){function p(s,t,x){if(t.length<=x)return[];var v=t[x],w=f(s,v,m,o,0);return[w].concat(p(b(s,
c(v,w)),t,++x))}return p([],n,0)}function i(n,m,o){function p(s,t,x){if(t.length<=x)return[];var v=t[x],w=-f(v,s,m,o,0);return[w].concat(p(b(c(v,w),s),t,++x))}n=l.call(n);return p([],n.reverse(),0).reverse()}function j(n,m,o,p){var s=g(n,m,o);n=i(n,m,o);if(p=="left")n=s;else if(p=="right")s=n;p=0;for(m=[];p<s.length;p++)m[p]=(s[p]+n[p])/2;return m}function k(n,m,o,p,s){function t(G,M,Q){var N=G.getData(aa,o),R=[],S=[],T=false,ba=(M||G.getData(W,o))+p.levelDistance;G.eachSubnode(function(D){if(D.exist&&
(!x||"$orn"in D.data&&D.data.$orn==s)){T||(T=a(n,p,D._depth,s,o));D=t(D,T[W],Q+ba);R.push(D.tree);S.push(D.extent)}});M=j(S,ca,da,ea);for(var H=0,X=[];H<R.length;H++){d(R[H],o,M[H],s);X.push(c(S[H],M[H]))}N=[[-N/2,N/2]].concat(e(X));G.getPos(o)[F]=0;if(s=="top"||s=="left")G.getPos(o)[B]=Q;else G.getPos(o)[B]=-Q;return{tree:G,extent:N}}var x=p.multitree,v=["x","y"],w=["width","height"],y=+(s=="left"||s=="right"),F=v[y],B=v[1-y],aa=w[y],W=w[1-y],da=p.siblingOffset,ca=p.subtreeOffset,ea=p.align;t(m,
false,0)}var l=Array.prototype.slice;return new q({compute:function(n,m){var o=n||"start",p=this.graph.getNode(this.root);h.extend(p,{drawn:true,exist:true,selected:true});$.compute(this.graph,o,this.config);if(m||!("_depth"in p))this.graph.computeLevels(this.root,0,"ignore");this.computePositions(p,o)},computePositions:function(n,m){var o=this.config,p=o.multitree,s=o.align,t=s!=="center"&&o.indent;o=o.orientation;var x=this;h.each(p?["top","right","bottom","left"]:[o],function(v){k(x.graph,n,m,
x.config,v,m);var w=["x","y"][+(v=="left"||v=="right")];(function y(F){F.eachSubnode(function(B){if(B.exist&&(!p||"$orn"in B.data&&B.data.$orn==v)){B.getPos(m)[w]+=F.getPos(m)[w];if(t)B.getPos(m)[w]+=s=="left"?t:-t;y(B)}})})(n)})}})}();$jit.ST=function(){function a(b){b=b||this.clickedNode;if(!this.config.constrained)return[];var e=this.geom,f=this.canvas,g=b._depth,i=[];this.graph.eachNode(function(j){if(j.exist&&!j.selected)if(j.isDescendantOf(b.id))j._depth<=g&&i.push(j);else i.push(j)});e=e.getRightLevelToShow(b,
f);b.eachLevel(e,e,function(j){j.exist&&!j.selected&&i.push(j)});for(e=0;e<c.length;e++){f=this.graph.getNode(c[e]);f.isDescendantOf(b.id)||i.push(f)}return i}function d(b){var e=[],f=this.config;b=b||this.clickedNode;this.clickedNode.eachLevel(0,f.levelsToShow,function(g){if(f.multitree&&!("$orn"in g.data)&&g.anySubnode(function(i){return i.exist&&!i.drawn}))e.push(g);else g.drawn&&!g.anySubnode("drawn")&&e.push(g)});return e}var c=[];return new q({Implements:[Z,E,V.Tree],initialize:function(b){var e=
$jit.ST;b=this.controller=this.config=h.merge(A("Canvas","Fx","Tree","Node","Edge","Controller","Tips","NodeStyles","Events","Navigation","Label"),{levelsToShow:2,levelDistance:30,constrained:true,Node:{type:"rectangle"},duration:700,offsetX:0,offsetY:0},b);if(b.useCanvas){this.canvas=b.useCanvas;this.config.labelContainer=this.canvas.id+"-label"}else{if(b.background)b.background=h.merge({type:"Circles"},b.background);this.canvas=new C(this,b);this.config.labelContainer=(typeof b.injectInto=="string"?
b.injectInto:b.injectInto.id)+"-label"}this.graphOptions={complex:true};this.graph=new r(this.graphOptions,this.config.Node,this.config.Edge);this.labels=new e.Label[b.Label.type](this);this.fx=new e.Plot(this,e);this.op=new e.Op(this);this.group=new e.Group(this);this.geom=new e.Geom(this);this.clickedNode=null;this.initializeExtras()},plot:function(){this.fx.plot(this.controller)},switchPosition:function(b,e,f){var g=this.geom,i=this.fx,j=this;if(!i.busy){i.busy=true;this.contract({onComplete:function(){g.switchOrientation(b);
j.compute("end",false);i.busy=false;if(e=="animate")j.onClick(j.clickedNode.id,f);else e=="replot"&&j.select(j.clickedNode.id,f)}},b)}},switchAlignment:function(b,e,f){this.config.align=b;if(e=="animate")this.select(this.clickedNode.id,f);else e=="replot"&&this.onClick(this.clickedNode.id,f)},addNodeInPath:function(b){c.push(b);this.select(this.clickedNode&&this.clickedNode.id||this.root)},clearNodesInPath:function(){c.length=0;this.select(this.clickedNode&&this.clickedNode.id||this.root)},refresh:function(){this.reposition();
this.select(this.clickedNode&&this.clickedNode.id||this.root)},reposition:function(){this.graph.computeLevels(this.root,0,"ignore");this.geom.setRightLevelToShow(this.clickedNode,this.canvas);this.graph.eachNode(function(b){if(b.exist)b.drawn=true});this.compute("end")},requestNodes:function(b,e){var f=h.merge(this.controller,e),g=this.config.levelsToShow;if(f.request){var i=[],j=b._depth;b.eachLevel(0,g,function(k){if(k.drawn&&!k.anySubnode()){i.push(k);k._level=g-(k._depth-j)}});this.group.requestNodes(i,
f)}else f.onComplete()},contract:function(b,e){var f=this.config.orientation,g=this.geom,i=this.group;e&&g.switchOrientation(e);var j=a.call(this);e&&g.switchOrientation(f);i.contract(j,h.merge(this.controller,b))},move:function(b,e){this.compute("end",false);var f=e.Move,g={x:f.offsetX,y:f.offsetY};f.enable&&this.geom.translate(b.endPos.add(g).$scale(-1),"end");this.fx.animate(h.merge(this.controller,{modes:["linear"]},e))},expand:function(b,e){this.group.expand(d.call(this,b),h.merge(this.controller,
e))},selectPath:function(b){function e(i){if(!(i==null||i.selected)){i.selected=true;h.each(f.group.getSiblings([i])[i.id],function(j){j.exist=true;j.drawn=true});i=i.getParents();i=i.length>0?i[0]:null;e(i)}}var f=this;this.graph.eachNode(function(i){i.selected=false});var g=0;for(b=[b.id].concat(c);g<b.length;g++)e(this.graph.getNode(b[g]))},setRoot:function(b,e,f){function g(){if(this.config.multitree&&l.data.$orn){var n={left:"right",right:"left",top:"bottom",bottom:"top"}[l.data.$orn];k.data.$orn=
n;(function m(o){o.eachSubnode(function(p){if(p.id!=b){p.data.$orn=n;m(p)}})})(k);delete l.data.$orn}this.root=b;this.clickedNode=l;this.graph.computeLevels(this.root,0,"ignore");this.geom.setRightLevelToShow(l,j,{execHide:false,onShow:function(m){if(!m.drawn){m.drawn=true;m.setData("alpha",1,"end");m.setData("alpha",0);m.pos.setc(l.pos.x,l.pos.y)}}});this.compute("end");this.busy=true;this.fx.animate({modes:["linear","node-property:alpha"],onComplete:function(){i.busy=false;i.onClick(b,{onComplete:function(){f&&
f.onComplete()}})}})}if(!this.busy){this.busy=true;var i=this,j=this.canvas,k=this.graph.getNode(this.root),l=this.graph.getNode(b);delete k.data.$orns;if(e=="animate"){g.call(this);i.selectPath(l)}else if(e=="replot"){g.call(this);this.select(this.root)}}},addSubtree:function(b,e,f){if(e=="replot")this.op.sum(b,h.extend({type:"replot"},f||{}));else if(e=="animate")this.op.sum(b,h.extend({type:"fade:seq"},f||{}))},removeSubtree:function(b,e,f,g){var i=[];this.graph.getNode(b).eachLevel(+!e,false,
function(j){i.push(j.id)});if(f=="replot")this.op.removeNode(i,h.extend({type:"replot"},g||{}));else if(f=="animate")this.op.removeNode(i,h.extend({type:"fade:seq"},g||{}))},select:function(b,e){var f=this.group,g=this.geom,i=this.graph.getNode(b),j=this.canvas;this.graph.getNode(this.root);var k=h.merge(this.controller,e),l=this;k.onBeforeCompute(i);this.selectPath(i);this.clickedNode=i;this.requestNodes(i,{onComplete:function(){f.hide(f.prepare(a.call(l)),k);g.setRightLevelToShow(i,j);l.compute("current");
l.graph.eachNode(function(n){var m=n.pos.getc(true);n.startPos.setc(m.x,m.y);n.endPos.setc(m.x,m.y);n.visited=false});l.geom.translate(i.endPos.add({x:k.offsetX,y:k.offsetY}).$scale(-1),["start","current","end"]);f.show(d.call(l));l.plot();k.onAfterCompute(l.clickedNode);k.onComplete()}})},onClick:function(b,e){var f=this.canvas,g=this,i=this.geom,j=this.config,k=h.merge(this.controller,{Move:{enable:true,offsetX:j.offsetX||0,offsetY:j.offsetY||0},setRightLevelToShowConfig:false,onBeforeRequest:h.empty,
onBeforeContract:h.empty,onBeforeMove:h.empty,onBeforeExpand:h.empty},e);if(!this.busy){this.busy=true;var l=this.graph.getNode(b);this.selectPath(l,this.clickedNode);this.clickedNode=l;k.onBeforeCompute(l);k.onBeforeRequest(l);this.requestNodes(l,{onComplete:function(){k.onBeforeContract(l);g.contract({onComplete:function(){i.setRightLevelToShow(l,f,k.setRightLevelToShowConfig);k.onBeforeMove(l);g.move(l,{Move:k.Move,onComplete:function(){k.onBeforeExpand(l);g.expand(l,{onComplete:function(){g.busy=
false;k.onAfterCompute(b);k.onComplete()}})}})}})}})}}})}();$jit.ST.$extend=true;$jit.ST.Op=new q({Implements:r.Op});$jit.ST.Group=new q({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.config=a.config;this.animation=new O;this.nodes=null},requestNodes:function(a,d){var c=0,b=a.length,e={},f=this.viz;b==0&&d.onComplete();for(var g=0;g<b;g++){e[a[g].id]=a[g];d.request(a[g].id,a[g]._level,{onComplete:function(i,j){if(j&&j.children){j.id=i;f.op.sum(j,{type:"nothing"})}if(++c==b){f.graph.computeLevels(f.root,
0);d.onComplete()}}})}},contract:function(a,d){var c=this;a=this.prepare(a);this.animation.setOptions(h.merge(d,{$animating:false,compute:function(b){if(b==1)b=0.99;c.plotStep(1-b,d,this.$animating);this.$animating="contract"},complete:function(){c.hide(a,d)}})).start()},hide:function(a,d){for(var c=0;c<a.length;c++)a[c].eachLevel(1,false,function(b){b.exist&&h.extend(b,{drawn:false,exist:false})});d.onComplete()},expand:function(a,d){var c=this;this.show(a);this.animation.setOptions(h.merge(d,{$animating:false,
compute:function(b){c.plotStep(b,d,this.$animating);this.$animating="expand"},complete:function(){c.plotStep(undefined,d,false);d.onComplete()}})).start()},show:function(a){var d=this.config;this.prepare(a);h.each(a,function(c){if(d.multitree&&!("$orn"in c.data)){delete c.data.$orns;var b=" ";c.eachSubnode(function(e){if("$orn"in e.data&&b.indexOf(e.data.$orn)<0&&e.exist&&!e.drawn)b+=e.data.$orn+" "});c.data.$orns=b}c.eachLevel(0,d.levelsToShow,function(e){if(e.exist)e.drawn=true})})},prepare:function(a){return this.nodes=
this.getNodesWithChildren(a)},getNodesWithChildren:function(a){var d=[],c=this.config;a.sort(function(g,i){return(g._depth<=i._depth)-(g._depth>=i._depth)});for(var b=0;b<a.length;b++)if(a[b].anySubnode("exist")){for(var e=b+1,f=false;!f&&e<a.length;e++)if(!c.multitree||"$orn"in a[e].data)f=f||a[b].isDescendantOf(a[e].id);f||d.push(a[b])}return d},plotStep:function(a,d,c){var b=this.viz,e=this.config,f=b.canvas.getCtx(),g=this.nodes,i,j,k={};for(i=0;i<g.length;i++){j=g[i];k[j.id]=[];var l=e.multitree&&
!("$orn"in j.data),n=l&&j.data.$orns;j.eachSubgraph(function(m){if(l&&n&&n.indexOf(m.data.$orn)>0&&m.drawn){m.drawn=false;k[j.id].push(m)}else if((!l||!n)&&m.drawn){m.drawn=false;k[j.id].push(m)}});j.drawn=true}g.length>0&&b.fx.plot();for(i in k)h.each(k[i],function(m){m.drawn=true});for(i=0;i<g.length;i++){j=g[i];f.save();b.fx.plotSubtree(j,d,a,c);f.restore()}},getSiblings:function(a){var d={};h.each(a,function(c){var b=c.getParents();if(b.length==0)d[c.id]=[c];else{var e=[];b[0].eachSubnode(function(f){e.push(f)});
d[c.id]=e}});return d}});$jit.ST.Geom=new q({Implements:r.Geom,switchOrientation:function(a){this.config.orientation=a},dispatch:function(){var a=Array.prototype.slice.call(arguments),d=a.shift(),c=a.length,b=function(e){return typeof e=="function"?e():e};if(c==2)return d=="top"||d=="bottom"?b(a[0]):b(a[1]);else if(c==4)switch(d){case "top":return b(a[0]);case "right":return b(a[1]);case "bottom":return b(a[2]);case "left":return b(a[3])}},getSize:function(a,d){var c=a.data,b=this.config,e=b.siblingOffset;
c=b.multitree&&"$orn"in c&&c.$orn||b.orientation;b=a.getData("width")+e;e=a.getData("height")+e;return d?this.dispatch(c,b,e):this.dispatch(c,e,b)},getTreeBaseSize:function(a,d,c){var b=this.getSize(a,true),e=0,f=this;if(c(d,a))return b;if(d===0)return 0;a.eachSubnode(function(g){e+=f.getTreeBaseSize(g,d-1,c)});return(b>e?b:e)+this.config.subtreeOffset},getEdge:function(a,d,c){var b=function(i,j){return function(){return a.pos.add(new u(i,j))}},e=this.node,f=a.getData("width"),g=a.getData("height");
if(d=="begin")if(e.align=="center")return this.dispatch(c,b(0,g/2),b(-f/2,0),b(0,-g/2),b(f/2,0));else if(e.align=="left")return this.dispatch(c,b(0,g),b(0,0),b(0,0),b(f,0));else if(e.align=="right")return this.dispatch(c,b(0,0),b(-f,0),b(0,-g),b(0,0));else throw"align: not implemented";else if(d=="end")if(e.align=="center")return this.dispatch(c,b(0,-g/2),b(f/2,0),b(0,g/2),b(-f/2,0));else if(e.align=="left")return this.dispatch(c,b(0,0),b(f,0),b(0,g),b(0,0));else if(e.align=="right")return this.dispatch(c,
b(0,-g),b(0,0),b(0,0),b(-f,0));else throw"align: not implemented";},getScaledTreePosition:function(a,d){var c=this.node,b=a.getData("width"),e=a.getData("height"),f=this.config.multitree&&"$orn"in a.data&&a.data.$orn||this.config.orientation,g=function(i,j){return function(){return a.pos.add(new u(i,j)).$scale(1-d)}};if(c.align=="left")return this.dispatch(f,g(0,e),g(0,0),g(0,0),g(b,0));else if(c.align=="center")return this.dispatch(f,g(0,e/2),g(-b/2,0),g(0,-e/2),g(b/2,0));else if(c.align=="right")return this.dispatch(f,
g(0,0),g(-b,0),g(0,-e),g(0,0));else throw"align: not implemented";},treeFitsInCanvas:function(a,d,c){d=d.getSize();d=this.dispatch(this.config.multitree&&"$orn"in a.data&&a.data.$orn||this.config.orientation,d.width,d.height);return this.getTreeBaseSize(a,c,function(b,e){return b===0||!e.anySubnode()})<d}});$jit.ST.Plot=new q({Implements:r.Plot,plotSubtree:function(a,d,c,b){var e=this.viz,f=e.canvas,g=e.config;c=Math.min(Math.max(0.0010,c),1);if(c>=0){a.drawn=false;f=f.getCtx();e=e.geom.getScaledTreePosition(a,
c);f.translate(e.x,e.y);f.scale(c,c)}this.plotTree(a,h.merge(d,{withLabels:true,hideLabels:!!c,plotSubtree:function(){var i=g.multitree&&!("$orn"in a.data),j=i&&a.getData("orns");return!i||j.indexOf(elem.getData("orn"))>-1}}),b);if(c>=0)a.drawn=true},getAlignedPos:function(a,d,c){var b=this.node;if(b.align=="center")a={x:a.x-d/2,y:a.y-c/2};else if(b.align=="left"){b=this.config.orientation;a=b=="bottom"||b=="top"?{x:a.x-d/2,y:a.y}:{x:a.x,y:a.y-c/2}}else if(b.align=="right"){b=this.config.orientation;
a=b=="bottom"||b=="top"?{x:a.x-d/2,y:a.y-c}:{x:a.x-d,y:a.y-c/2}}else throw"align: not implemented";return a},getOrientation:function(a){var d=this.config,c=d.orientation;if(d.multitree){d=a.nodeFrom;a=a.nodeTo;c="$orn"in d.data&&d.data.$orn||"$orn"in a.data&&a.data.$orn}return c}});$jit.ST.Label={};$jit.ST.Label.Native=new q({Implements:r.Label.Native,renderLabel:function(a,d){var c=a.getCtx(),b=d.pos.getc(true);c.fillText(d.name,b.x,b.y)}});$jit.ST.Label.DOM=new q({Implements:r.Label.DOM,placeLabel:function(a,
d,c){var b=d.pos.getc(true),e=this.viz.config,f=e.Node,g=this.viz.canvas,i=d.getData("width"),j=d.getData("height"),k=g.getSize(),l=b.x*g.scaleOffsetX+g.translateOffsetX;b=b.y*g.scaleOffsetY+g.translateOffsetY;if(f.align=="center")i={x:Math.round(l-i/2+k.width/2),y:Math.round(b-j/2+k.height/2)};else if(f.align=="left"){e=e.orientation;i=e=="bottom"||e=="top"?{x:Math.round(l-i/2+k.width/2),y:Math.round(b+k.height/2)}:{x:Math.round(l+k.width/2),y:Math.round(b-j/2+k.height/2)}}else if(f.align=="right"){e=
e.orientation;i=e=="bottom"||e=="top"?{x:Math.round(l-i/2+k.width/2),y:Math.round(b-j+k.height/2)}:{x:Math.round(l-i+k.width/2),y:Math.round(b-j/2+k.height/2)}}else throw"align: not implemented";j=a.style;j.left=i.x+"px";j.top=i.y+"px";j.display=this.fitsInCanvas(i,g)?"":"none";c.onPlaceLabel(a,d)}});$jit.ST.Label.SVG=new q({Implements:[$jit.ST.Label.DOM,r.Label.SVG],initialize:function(a){this.viz=a}});$jit.ST.Label.HTML=new q({Implements:[$jit.ST.Label.DOM,r.Label.HTML],initialize:function(a){this.viz=
a}});$jit.ST.Plot.NodeTypes=new q({none:{render:h.empty,contains:h.lambda(false)},circle:{render:function(a,d){var c=a.getData("dim"),b=this.getAlignedPos(a.pos.getc(true),c,c);c=c/2;this.nodeHelper.circle.render("fill",{x:b.x+c,y:b.y+c},c,d)},contains:function(a){var d=a.getData("dim");a=this.getAlignedPos(a.pos.getc(true),d,d);d=d/2;this.nodeHelper.circle.contains({x:a.x+d,y:a.y+d},d)}},square:{render:function(a,d){var c=a.getData("dim"),b=c/2;c=this.getAlignedPos(a.pos.getc(true),c,c);this.nodeHelper.square.render("fill",
{x:c.x+b,y:c.y+b},b,d)},contains:function(a){var d=a.getData("dim");a=this.getAlignedPos(a.pos.getc(true),d,d);d=d/2;this.nodeHelper.square.contains({x:a.x+d,y:a.y+d},d)}},ellipse:{render:function(a,d){var c=a.getData("width"),b=a.getData("height"),e=this.getAlignedPos(a.pos.getc(true),c,b);this.nodeHelper.ellipse.render("fill",{x:e.x+c/2,y:e.y+b/2},c,b,d)},contains:function(a){var d=a.getData("width"),c=a.getData("height");a=this.getAlignedPos(a.pos.getc(true),d,c);this.nodeHelper.ellipse.contains({x:a.x+
d/2,y:a.y+c/2},d,c,canvas)}},rectangle:{render:function(a,d){var c=a.getData("width"),b=a.getData("height"),e=this.getAlignedPos(a.pos.getc(true),c,b);this.nodeHelper.rectangle.render("fill",{x:e.x+c/2,y:e.y+b/2},c,b,d)},contains:function(a){var d=a.getData("width"),c=a.getData("height");a=this.getAlignedPos(a.pos.getc(true),d,c);this.nodeHelper.rectangle.contains({x:a.x+d/2,y:a.y+c/2},d,c,canvas)}}});$jit.ST.Plot.EdgeTypes=new q({none:h.empty,line:{render:function(a,d){var c=this.getOrientation(a),
b=a.nodeFrom,e=a.nodeTo,f=b._depth<e._depth,g=this.viz.geom.getEdge(f?b:e,"begin",c);c=this.viz.geom.getEdge(f?e:b,"end",c);this.edgeHelper.line.render(g,c,d)},contains:function(a,d){var c=this.getOrientation(a),b=a.nodeFrom,e=a.nodeTo,f=b._depth<e._depth,g=this.viz.geom.getEdge(f?b:e,"begin",c);c=this.viz.geom.getEdge(f?e:b,"end",c);return this.edgeHelper.line.contains(g,c,d,this.edge.epsilon)}},arrow:{render:function(a,d){var c=this.getOrientation(a),b=a.nodeFrom,e=a.nodeTo,f=a.getData("dim"),g=
this.viz.geom.getEdge(b,"begin",c);c=this.viz.geom.getEdge(e,"end",c);e=a.data.$direction;this.edgeHelper.arrow.render(g,c,f,e&&e.length>1&&e[0]!=b.id,d)},contains:function(a,d){var c=this.getOrientation(a),b=a.nodeFrom,e=a.nodeTo,f=b._depth<e._depth,g=this.viz.geom.getEdge(f?b:e,"begin",c);c=this.viz.geom.getEdge(f?e:b,"end",c);return this.edgeHelper.arrow.contains(g,c,d,this.edge.epsilon)}},"quadratic:begin":{render:function(a,d){var c=this.getOrientation(a),b=a.nodeFrom,e=a.nodeTo,f=b._depth<e._depth,
g=this.viz.geom.getEdge(f?b:e,"begin",c);b=this.viz.geom.getEdge(f?e:b,"end",c);e=a.getData("dim");f=d.getCtx();f.beginPath();f.moveTo(g.x,g.y);switch(c){case "left":f.quadraticCurveTo(g.x+e,g.y,b.x,b.y);break;case "right":f.quadraticCurveTo(g.x-e,g.y,b.x,b.y);break;case "top":f.quadraticCurveTo(g.x,g.y+e,b.x,b.y);break;case "bottom":f.quadraticCurveTo(g.x,g.y-e,b.x,b.y);break}f.stroke()}},"quadratic:end":{render:function(a,d){var c=this.getOrientation(a),b=a.nodeFrom,e=a.nodeTo,f=b._depth<e._depth,
g=this.viz.geom.getEdge(f?b:e,"begin",c);b=this.viz.geom.getEdge(f?e:b,"end",c);e=a.getData("dim");f=d.getCtx();f.beginPath();f.moveTo(g.x,g.y);switch(c){case "left":f.quadraticCurveTo(b.x-e,b.y,b.x,b.y);break;case "right":f.quadraticCurveTo(b.x+e,b.y,b.x,b.y);break;case "top":f.quadraticCurveTo(b.x,b.y-e,b.x,b.y);break;case "bottom":f.quadraticCurveTo(b.x,b.y+e,b.x,b.y);break}f.stroke()}},bezier:{render:function(a,d){var c=this.getOrientation(a),b=a.nodeFrom,e=a.nodeTo,f=b._depth<e._depth,g=this.viz.geom.getEdge(f?
b:e,"begin",c);b=this.viz.geom.getEdge(f?e:b,"end",c);e=a.getData("dim");f=d.getCtx();f.beginPath();f.moveTo(g.x,g.y);switch(c){case "left":f.bezierCurveTo(g.x+e,g.y,b.x-e,b.y,b.x,b.y);break;case "right":f.bezierCurveTo(g.x-e,g.y,b.x+e,b.y,b.x,b.y);break;case "top":f.bezierCurveTo(g.x,g.y+e,b.x,b.y-e,b.x,b.y);break;case "bottom":f.bezierCurveTo(g.x,g.y-e,b.x,b.y+e,b.x,b.y);break}f.stroke()}}})})();
